### PR TITLE
add codecov

### PR DESCRIPTION
**Pull request by stevenysw**

### CODE REVIEW

**Comment by daattali** [comment]
Good call, thanks!

**Comment by daattali** [comment]
I'm assuming you've used covr with travis before? I just went to https://codecov.io/github/ropensci/ezknitr?branch=master to check the status, and it says I don't have permission. Do you know how to fix that?

**Comment by klmr** [comment]
@daattali It works for me …

**Comment by daattali** [comment]
ok, yes, I can see it now. Looks like it took a few hours to kick in

**Pull request merged**
